### ISSUE TITLE
Email addresses should not be public

### ISSUE THREAD

**Issue by stuartyeates** [danielBingham/peerreview#132]
**Describe the bug**

Email addresses should not be public.

**To Reproduce**
1. create an account with an email address
2. go to https://staging.peer-review.io/user/15 in a new browser session
3. notice that the email is public

**Expected behavior**
Either don't display the mail at all or display it as "withheld".

Consider reading https://www.w3.org/TR/app-privacy-bp/

**Comment by danielBingham** [comment]
Yep!  This had been on my mental to do but hadn't made it into the issue backlog yet.  Thanks for capturing it! I'll work on it today, since we're basically doing a public alpha, it probably should be fixed ASAP.

Eventual plan is to allow multiple emails per account and allow people to select visibility for each email, but in the mean time we'll just hide them.
